# Generated by Django 3.2.8 on 2021-10-21 21:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_study', '0002_rename_post_case'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='Post',
        ),
    ]
